### ISSUE TITLE
JS regression: minified pdfmake errors

### ISSUE THREAD

**Issue by jpodeszfa** [tdewolff/minify#509] opened 2022-07-01 11:36 UTC
I have encountered some problems with minified https://github.com/bpampuch/pdfmake (version [0.2.5](https://github.com/bpampuch/pdfmake/archive/refs/tags/0.2.5.tar.gz)). It used to work in minify version [v2.10.0](https://github.com/tdewolff/minify/releases/tag/v2.10.0). Unfortunately, I could not prepare a minimal example.

File minified with command:
```bash
minify build/pdfmake.js
```

chrome error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'getHighWaterMark')
at 6577 (pdfmake.js:182:11415)
at e (pdfmake.js:194:140975)
at 2830 (pdfmake.js:182:6392)
at e (pdfmake.js:194:140975)
at 1680 (pdfmake.js:55:11696)
at e (pdfmake.js:194:140975)
at 6079 (pdfmake.js:194:15815)
at e (pdfmake.js:194:140975)
at 8617 (pdfmake.js:194:15977)
at e (pdfmake.js:194:140975)
```

git bisect output:

e7fcbe962be6115c98bb8b2d6fdd7fb8f388d6c4 is the first bad commit
commit e7fcbe962be6115c98bb8b2d6fdd7fb8f388d6c4
Author: Taco de Wolff <tacodewolff@gmail.com>
Date:   Sat Apr 2 14:48:10 2022 -0300

    JS: merge sequential var declarations into another declaration

It appears, that this error does not occur with `--js-keep-var-names` parameter, but another error was encountered.

File minified with command:
```bash
minify --js-keep-var-names build/pdfmake.js
```

chrome error:
```
Uncaught (in promise) Error: SVGMeasure: Error: Attribute without value
Line: 0
Column: 66
Char: =
    at parseSVG (pdfmake.js:194:54321)
    at SVGMeasure.measureSVG (pdfmake.js:194:54520)
    at DocMeasure.measureSVG (pdfmake.js:193:19786)
    at pdfmake.js:193:16411
    at StyleContextStack.auto (pdfmake.js:194:53464)
    at DocMeasure.measureNode (pdfmake.js:193:15812)
    at DocMeasure.measureVerticalContainer (pdfmake.js:193:21494)
    at pdfmake.js:193:15970
    at StyleContextStack.auto (pdfmake.js:194:53464)
    at DocMeasure.measureNode (pdfmake.js:193:15812)
```

git bisect output:

ff4ee8ba721967e311f507c01b41bec6555fe63c is the first bad commit
commit ff4ee8ba721967e311f507c01b41bec6555fe63c
Author: Taco de Wolff <tacodewolff@gmail.com>
Date:   Sat May 28 09:27:37 2022 -0400

    JS: use template literals when shorter than double/single quoted strings

Sample web page to reproduce errors:
```html
<!DOCTYPE html>
<script src="pdfmake.js"></script>
<script src="vfs_fonts.js"></script>
<script>
  var emc2 = '<svg xmlns="http://www.w3.org/2000/svg" version="1.1"><g><text x = "10" y = "25" font-size = "20"><tspan>e = mc<tspan baseline-shift = "super">2</tspan>        </tspan>        <tspan x = "10" y = "60">            T             <tspan baseline-shift = "sub">i+2</tspan>=T<tspan baseline-shift = "sub">i</tspan> + T <tspan baseline-shift = "sub">i+1</tspan></tspan></text></g>';

  pdfMake.createPdf({
    pageSize: 'A4',
    content: [
      'test',
      {
        svg: emc2,
      }
    ]
  }).open();
</script>

```

**Comment by tdewolff** [comment] 2022-07-01 16:58
Thanks for raising the issue, I will look into both cases

**Comment by tdewolff** [comment] 2022-07-01 21:21
The first bug has been fixed with the commit above. The other bug was actually caused by https://github.com/tdewolff/minify/commit/a66515866912e7c4bfc38e1a04866efe2385e05d

**Comment by tdewolff** [comment] 2022-07-01 22:15
Fixed! Thanks for bringing this up

**Closed** 2022-07-01 22:15 UTC
