### ISSUE TITLE
go get return an error

### ISSUE THREAD

**Issue by segeschecho** [tdewolff/minify#232] opened 2018-11-07 20:36 UTC
Hi!,

I am trying to install minify, but I'm getting an error running go get:

`go get -u github.com/tdewolff/minify`

It can not find some dependencies. I attach the results I get:

>` package github.com/tdewolff/parse/v2: cannot find package "github.com/tdewolff/parse/v2"`

> `package github.com/tdewolff/parse/v2/buffer: cannot find package "github.com/tdewolff/parse/v2/buffer"`

> `package github.com/tdewolff/parse/v2/strconv: cannot find package "github.com/tdewolff/parse/v2/strconv"`

Is it possible that I miss some extra step to perform the installation ?

Thanks in advance !

**Comment by tdewolff** [comment] 2018-11-07 20:49
Hi @segeschecho, what Go version are you running?

**Comment by segeschecho** [comment] 2018-11-07 20:51
Hi! I'm running go 1.9.2

**Comment by shlomif** [comment] 2018-11-07 21:11
I am getting a very similar error on Ubuntu x86-64 14.04 and Travis-CI - see https://travis-ci.community/t/go-get-u-github-com-tdewolff-minify-cmd-minify-started-failing-on-linux/724 . This is breaking my builds.

**Comment by tdewolff** [comment] 2018-11-07 21:44
This whole Go modules thing has been a major PITA, but now it should be working if you use it right.

The problem is that Go versions under 1.9.7 and 1.10.3 DO NOT support major versions in the import path (ie. `/v2` at the end of the import path), but they MUST BE present for Go modules to work. So in order to support Go modules, these import paths have `/v2` appended, but that means that older Go versions do not understand those paths. In hindsight, by adding filepaths for `v2` this could've been prevented but it's a little late for that now.

If you cannot upgrade to Go 1.9.7+, 1.10.3+ or 1.11, then please DOWNGRADE to **minify@v2.3.6** and **parse@v2.3.4**. If you ARE using those newer Go versions, please UPGRADE to the latest versions.

@shlomif you are using go1.8.3, you need to pin to older version for both `minify` and `parse`, @segeschecho you too, or upgrade Go.

**Comment by shlomif** [comment] 2018-11-08 09:37
@tdewolff : upgrading golang to 1.11 seems to fix it - thanks!

**Comment by monoflash** [comment] 2018-11-08 14:04
```
$ go version
go version go1.11.1 darwin/amd64
```

Why are you talking about versions of golang?
The problem is not the version of golang, problem in the organization of your library!
Make a normal repository for the library, go at least to gopkg.in !!!

Create the versioning of library correct!

I so foolishly decided to update the package dependencies ... :(
And now all your code does not work.

And apparently, I will have to fork your repository and place it in the correct form so that everything works.

Sadly!

**Comment by SelfEnergy** [comment] 2018-11-11 09:59
Get the same error under Gentoo using Go version 1.11.2
`package github.com/tdewolff/minify/v2: cannot find package "github.com/tdewolff/minify/v2" in any of:
        /usr/lib/go/src/github.com/tdewolff/minify/v2 (from $GOROOT)
        /home/MyUser/go/src/github.com/tdewolff/minify/v2 (from $GOPATH)`

Here the result of an ls for  /home/MyUser/go/src/github.com/tdewolff/minify/
`benchmarks  cmd  common.go  common_test.go  css  go.mod  go.sum  html  js  json  LICENSE.md  minify.go  minify_test.go  README.md  svg  xml`

**Comment by tdewolff** [comment] 2018-11-11 19:43
Could it be that `GO111MODULES` is not `on`?

This whole Go modules has been a major pain so far :(

**Comment by SelfEnergy** [comment] 2018-11-11 23:18
Thanks, this was indeed the issue!

The easiest solution for me was to create a dummy temporary module and then use the go get command. This will cause go in version 1.11 to fetch the package correctly.

Setting GO111MODULES=on is then not required explicitly and will anyhow not work in version 1.11 without the presence of a go-module in the current folder. This inconvenience is as far as I know planned to be fixed in go 1.12. ([Go Issue 24250](https://github.com/golang/go/issues/24250))

**Closed** 2018-12-09 23:29 UTC

**Comment by codemodify** [comment] 2019-01-01 20:51
> Thanks, this was indeed the issue!
> 
> The easiest solution for me was to create a dummy temporary module and then use the go get command. This will cause go in version 1.11 to fetch the package correctly.
> 
> Setting GO111MODULES=on is then not required explicitly and will anyhow not work in version 1.11 without the presence of a go-module in the current folder. This inconvenience is as far as I know planned to be fixed in go 1.12. ([Go Issue 24250](https://github.com/golang/go/issues/24250))

Can you show examples of what you did ?
