### ISSUE TITLE
HTML Minifer invalidates certain meta tags

### ISSUE THREAD

**Issue by b3ntly** [tdewolff/minify#236] opened 2018-12-04 18:51 UTC
Great library but I found an edge case.

The Open Graph Protocol specifies HTML Meta tags for describing attributes of a webpage and is used by Facebook, Twitter, LinkedIn, etc. for LinkedIn, for content preview for articles, links, etc.

After applying the default HTML minimizer to the following code LinkedIn was unable to parse meta tags in this format:

```
<meta name="type" property="og:type" content="website" />
```

Disabling the minifier solved the problem.

**Comment by tdewolff** [comment] 2018-12-04 19:42
Do you use Hugo? Otherwise, enabling `KeepDocumentTags` might solve this. Please let me know if that solves it (in which case the parser of LinkedIn does not work properly with HTML5).

The quoted piece of HTML is minified in the same way as other minifiers, so I think the problem is in its surroundings.

**Comment by b3ntly** [comment] 2018-12-05 02:08
Thanks for the quick response! I'll dig into this soon :tm , I would not be the least surprised if the $2billion company responsible is failing to scrape my site properly.

**Comment by b3ntly** [comment] 2018-12-10 00:01
I'll be reviewing our various previews on social media again this week so I should have an update then. Much appreciation to a maintainer who takes the time to follow-up on such issues. :)

**Comment by rioastamal** [comment] 2018-12-15 08:48
What'sApp and Facebook are not happy when we remove quote on property name.

```html
...
<meta property=og:description content="Some content goes here">
...
```

They did not correctly parse the description when there is no quote for "og:description". When I add the quote manually What'sApp and Facebook able to display the description content.

It you test it on Facebook Debugger it parse correctly, but if you post the link on your Timeline it does not work. Same goes for What'sApp.

I try to run

```
$ minify --html-keep-document-tags
```

But it still removes the quote.

**Comment by tdewolff** [comment] 2018-12-16 20:59
Are both `meta` tags not parse correctly, or only the one with the color? In any case, it is perfectly valid to unquote colon characters since a long time. I'm suspecting WhatsApp/FB parses HTML as XML, which is a very bad thing (they are different languages all together). Just to be sure, the HTML files have `<!doctype html>` at the top so it is a HTML5 document?

Can you name the exact feature in WhatsApp and Facebook that parses your HTML? I'd like to try it myself and perhaps raise an issue there.

**Comment by rioastamal** [comment] 2018-12-27 22:44
@tdewolff Both tag are not parsed correctly.

I do not know the name of the feature on WhatsApp I guess it's called Link Share. Try to share these two links to see the different on WhatsApp.

https://rioastamal.net/test-share/with-quote.html
https://rioastamal.net/test-share/without-quote.html

**Comment by tdewolff** [comment] 2019-03-15 19:23
It appears that attributes from the Open Graph Protocol are XHTML for some reason, and not HTML5. This probably means that (some) attributes need to have double-quotes and the tag should be closed properly (either by `<tag />` or by `<tag></tag>`). This seems to apply to mostly `meta` tag attributes, but maybe also the `prefix` attribute.

I don't want this to become an option to switch off quote removal, I want to minifier to automatically keep quotes around attributes that require it.

**Comment by tdewolff** [comment] 2019-03-15 21:18
It should now keep double quotes on some attributes, that should be sufficient to fix the problems. Can this be confirmed? @b3ntly @rioastamal 

@Jos512 Can you confirm too? It might be that the `name` attribute needs explicit double quotes too

**Comment by Jos512** [comment] 2019-03-20 15:49
> PS: is this useful? https://gist.github.com/kevinSuttle/1997924

I don't think so since it's updated last in October 2015. And there entries there that work find without quotes (like `description`, `stylesheet`, and `canonical`).

> Can you confirm too? It might be that the name attribute needs explicit double quotes too

Bing doesn't specify in their [webmaster verification help page](https://www.bing.com/webmaster/help/how-to-verify-ownership-of-your-site-afcfefc6) that they expect double quotes or a particular markup. 

With a bit more Googling I did find [this](https://blogs.bing.com/webmaster/2010/03/25/meta-tag-authentication-frustration-resolved-from-the-forums) old (March 2010) in which someone from the *Bing Webmaster Center* team writes:

> In addition, Webmaster Center does look for the proper XHTML-based closing of the <meta> tag – the ” />”, so be sure to use this closing in your code.

This would suggest that the Bing verification has to be XHTML-valid, so with double-quotes. (I could not find a more recent source.)

> I don't want this to become an option to switch off quote removal, I want to minifier to automatically keep quotes around attributes that require it.

How about adding a rule like "if there's an attribute in `<head>` that ends with `/>`, don't remove quotes"?

Admittedly, this moves towards an option feature. But I think it's easier to maintain for you than working with a blacklist of attributes that should not be minified. Plus, with a blacklist we're always running behind if some other attribute pops up that requires double quotes.

If this option gets mentioned in the README, people can also troubleshoot themselves by adding `/` to the end of their `<head>` attribute, which can lessen support requests in the future.

**Comment by tdewolff** [comment] 2019-03-20 17:20
Thanks for the thorough reply! I indeed found the same old message from the Bing Webmaster Center. They don't specify the grammer though because they use the RDFa specification, which is maintained by W3.org. All the other applications seem to be using this as well. This RDFa specification is pretty clear and does not change that frequently, so I prefer to follow that if possible. The blacklist should be complete and also apply to tags in `<body>`, I think the running behind in adding attributes will not be a problem as not many are ever added (the spec moves slowly).

Hopefully the implementation is sufficient now, so that Bing, Facebook and WhatsApp work but I need confirmation from everybody if possible.

**Comment by rioastamal** [comment] 2019-03-20 21:13
@tdewolff I can confirm that now it is working on WhatsApp. But it would be great that we have options to disable quote removal inside head tag.

Thanks 👍

**Comment by tdewolff** [comment] 2019-04-05 21:34
I'm assuming this is fixed now, otherwise please re-open!

**Closed by tdewolff** 2019-04-05 21:34 UTC
