### ISSUE TITLE
Increasing svg size after minify

### ISSUE THREAD

**Issue by MichaelMonashev** [tdewolff/minify#196] opened 2018-04-14 06:08 UTC
Example:
before 2859 bytes
```
<!doctype html><html lang=en><title>Document</title><style>body{background-color:#fff;background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='100%25' height='100%25' viewBox='0 0 800 800'%3E%3Cdefs%3E%3CradialGradient id='a' cx='400' cy='400' r='50%25' gradientUnits='userSpaceOnUse'%3E%3Cstop offset='0' stop-color='%23FFF'/%3E%3Cstop offset='1' stop-color='%230EF'/%3E%3C/radialGradient%3E%3CradialGradient id='b' cx='400' cy='400' r='70%25' gradientUnits='userSpaceOnUse'%3E%3Cstop offset='0' stop-color='%23FFF'/%3E%3Cstop offset='1' stop-color='%230FF'/%3E%3C/radialGradient%3E%3C/defs%3E%3Crect fill='url(%23a)' width='800' height='800'/%3E%3Cg fill-opacity='.8'%3E%3Cpath fill='url(%23b)' d='M998.7%2C439.2c1.7-26.5%2C1.7-52.7%2C0.1-78.5L401%2C399.9c0%2C0%2C0-0.1%2C0-0.1l587.6-116.9c-5.1-25.9-11.9-51.2-20.3-75.8L400.9%2C399.7c0%2C0%2C0-0.1%2C0-0.1l537.3-265c-11.6-23.5-24.8-46.2-39.3-67.9L400.8%2C399.5c0%2C0%2C0-0.1-0.1-0.1l450.4-395c-17.3-19.7-35.8-38.2-55.5-55.5l-395%2C450.4c0%2C0-0.1%2C0-0.1-0.1L733.4-99c-21.7-14.5-44.4-27.6-68-39.3l-265%2C537.4c0%2C0-0.1%2C0-0.1%2C0l192.6-567.4c-24.6-8.3-49.9-15.1-75.8-20.2L400.2%2C399c0%2C0-0.1%2C0-0.1%2C0l39.2-597.7c-26.5-1.7-52.7-1.7-78.5-0.1L399.9%2C399c0%2C0-0.1%2C0-0.1%2C0L282.9-188.6c-25.9%2C5.1-51.2%2C11.9-75.8%2C20.3l192.6%2C567.4c0%2C0-0.1%2C0-0.1%2C0l-265-537.3c-23.5%2C11.6-46.2%2C24.8-67.9%2C39.3l332.8%2C498.1c0%2C0-0.1%2C0-0.1%2C0.1L4.4-51.1C-15.3-33.9-33.8-15.3-51.1%2C4.4l450.4%2C395c0%2C0%2C0%2C0.1-0.1%2C0.1L-99%2C66.6c-14.5%2C21.7-27.6%2C44.4-39.3%2C68l537.4%2C265c0%2C0%2C0%2C0.1%2C0%2C0.1l-567.4-192.6c-8.3%2C24.6-15.1%2C49.9-20.2%2C75.8L399%2C399.8c0%2C0%2C0%2C0.1%2C0%2C0.1l-597.7-39.2c-1.7%2C26.5-1.7%2C52.7-0.1%2C78.5L399%2C400.1c0%2C0%2C0%2C0.1%2C0%2C0.1l-587.6%2C116.9c5.1%2C25.9%2C11.9%2C51.2%2C20.3%2C75.8l567.4-192.6c0%2C0%2C0%2C0.1%2C0%2C0.1l-537.3%2C265c11.6%2C23.5%2C24.8%2C46.2%2C39.3%2C67.9l498.1-332.8c0%2C0%2C0%2C0.1%2C0.1%2C0.1l-450.4%2C395c17.3%2C19.7%2C35.8%2C38.2%2C55.5%2C55.5l395-450.4c0%2C0%2C0.1%2C0%2C0.1%2C0.1L66.6%2C899c21.7%2C14.5%2C44.4%2C27.6%2C68%2C39.3l265-537.4c0%2C0%2C0.1%2C0%2C0.1%2C0L207.1%2C968.3c24.6%2C8.3%2C49.9%2C15.1%2C75.8%2C20.2L399.8%2C401c0%2C0%2C0.1%2C0%2C0.1%2C0l-39.2%2C597.7c26.5%2C1.7%2C52.7%2C1.7%2C78.5%2C0.1L400.1%2C401c0%2C0%2C0.1%2C0%2C0.1%2C0l116.9%2C587.6c25.9-5.1%2C51.2-11.9%2C75.8-20.3L400.3%2C400.9c0%2C0%2C0.1%2C0%2C0.1%2C0l265%2C537.3c23.5-11.6%2C46.2-24.8%2C67.9-39.3L400.5%2C400.8c0%2C0%2C0.1%2C0%2C0.1-0.1l395%2C450.4c19.7-17.3%2C38.2-35.8%2C55.5-55.5l-450.4-395c0%2C0%2C0-0.1%2C0.1-0.1L899%2C733.4c14.5-21.7%2C27.6-44.4%2C39.3-68l-537.4-265c0%2C0%2C0-0.1%2C0-0.1l567.4%2C192.6c8.3-24.6%2C15.1-49.9%2C20.2-75.8L401%2C400.2c0%2C0%2C0-0.1%2C0-0.1L998.7%2C439.2z'/%3E%3C/g%3E%3C/svg%3E");background-attachment:fixedabackground-size:cover;background-position:center;}</style>ZZZZZZZZz
```

after 2997 bytes:
```
<!doctype html><html lang=en><title>Document</title><style>body{background-color:#fff;background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA4MDAgODAwIj48ZGVmcz48cmFkaWFsR3JhZGllbnQgaWQ9ImEiIGN4PSI0MDAiIGN5PSI0MDAiIHI9IjUwJSIgZ3JhZGllbnRVbml0cz0idXNlclNwYWNlT25Vc2UiPjxzdG9wIG9mZnNldD0iMCIgc3RvcC1jb2xvcj0iI2ZmZiIvPjxzdG9wIG9mZnNldD0iMSIgc3RvcC1jb2xvcj0iIzBlZiIvPjwvcmFkaWFsR3JhZGllbnQ+PHJhZGlhbEdyYWRpZW50IGlkPSJiIiBjeD0iNDAwIiBjeT0iNDAwIiByPSI3MCUiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj48c3RvcCBvZmZzZXQ9IjAiIHN0b3AtY29sb3I9IiNmZmYiLz48c3RvcCBvZmZzZXQ9IjEiIHN0b3AtY29sb3I9IiMwZmYiLz48L3JhZGlhbEdyYWRpZW50PjwvZGVmcz48cGF0aCBmaWxsPSJ1cmwoI2EpIiBkPSJNMCAwaDhlMnY4ZTJIMHoiLz48ZyBmaWxsLW9wYWNpdHk9Ii44Ij48cGF0aCBmaWxsPSJ1cmwoI2IpIiBkPSJNOTk4LjcgNDM5LjJjMS43LTI2LjUgMS43LTUyLjcuMS03OC41TDQwMSAzOTkuOWMwIDAgMC0uMS4wLS4xbDU4Ny42LTExNi45Yy01LjEtMjUuOS0xMS45LTUxLjItMjAuMy03NS44TDQwMC45IDM5OS43YzAgMCAwLS4xLjAtLjFsNTM3LjMtMjY1Yy0xMS42LTIzLjUtMjQuOC00Ni4yLTM5LjMtNjcuOUw0MDAuOCAzOTkuNWMwIDAgMC0uMS0uMS0uMWw0NTAuNC0zOTVjLTE3LjMtMTkuNy0zNS44LTM4LjItNTUuNS01NS41bC0zOTUgNDUwLjRjMCAwLS4xLjAtLjEtLjFMNzMzLjQtOTljLTIxLjctMTQuNS00NC40LTI3LjYtNjgtMzkuM2wtMjY1IDUzNy40YzAgMC0uMS4wLS4xLjBsMTkyLjYtNTY3LjRjLTI0LjYtOC4zLTQ5LjktMTUuMS03NS44LTIwLjJMNDAwLjIgMzk5YzAgMC0uMS4wLS4xLjBsMzkuMi01OTcuN2MtMjYuNS0xLjctNTIuNy0xLjctNzguNS0uMUwzOTkuOSAzOTljMCAwLS4xLjAtLjEuMEwyODIuOS0xODguNmMtMjUuOSA1LjEtNTEuMiAxMS45LTc1LjggMjAuM2wxOTIuNiA1NjcuNGMwIDAtLjEuMC0uMS4wbC0yNjUtNTM3LjNjLTIzLjUgMTEuNi00Ni4yIDI0LjgtNjcuOSAzOS4zbDMzMi44IDQ5OC4xYzAgMC0uMS4wLS4xLjFMNC40LTUxLjFDLTE1LjMtMzMuOS0zMy44LTE1LjMtNTEuMSA0LjRsNDUwLjQgMzk1YzAgMCAwIC4xLS4xLjFMLTk5IDY2LjZjLTE0LjUgMjEuNy0yNy42IDQ0LjQtMzkuMyA2OGw1MzcuNCAyNjVjMCAwIDAgLjEuMC4xbC01NjcuNC0xOTIuNmMtOC4zIDI0LjYtMTUuMSA0OS45LTIwLjIgNzUuOEwzOTkgMzk5LjhjMCAwIDAgLjEuMC4xbC01OTcuNy0zOS4yYy0xLjcgMjYuNS0xLjcgNTIuNy0uMSA3OC41TDM5OSA0MDAuMWMwIDAgMCAuMS4wLjFsLTU4Ny42IDExNi45YzUuMSAyNS45IDExLjkgNTEuMiAyMC4zIDc1LjhsNTY3LjQtMTkyLjZjMCAwIDAgLjEuMC4xbC01MzcuMyAyNjVjMTEuNiAyMy41IDI0LjggNDYuMiAzOS4zIDY3LjlsNDk4LjEtMzMyLjhjMCAwIDAgLjEuMS4xbC00NTAuNCAzOTVjMTcuMyAxOS43IDM1LjggMzguMiA1NS41IDU1LjVsMzk1LTQ1MC40YzAgMCAuMS4wLjEuMUw2Ni42IDg5OWMyMS43IDE0LjUgNDQuNCAyNy42IDY4IDM5LjNsMjY1LTUzNy40YzAgMCAuMS4wLjEuMEwyMDcuMSA5NjguM2MyNC42IDguMyA0OS45IDE1LjEgNzUuOCAyMC4yTDM5OS44IDQwMWMwIDAgLjEuMC4xLjBsLTM5LjIgNTk3LjdjMjYuNSAxLjcgNTIuNyAxLjcgNzguNS4xTDQwMC4xIDQwMWMwIDAgLjEuMC4xLjBsMTE2LjkgNTg3LjZjMjUuOS01LjEgNTEuMi0xMS45IDc1LjgtMjAuM0w0MDAuMyA0MDAuOWMwIDAgLjEuMC4xLjBsMjY1IDUzNy4zYzIzLjUtMTEuNiA0Ni4yLTI0LjggNjcuOS0zOS4zTDQwMC41IDQwMC44YzAgMCAuMS4wLjEtLjFsMzk1IDQ1MC40YzE5LjctMTcuMyAzOC4yLTM1LjggNTUuNS01NS41bC00NTAuNC0zOTVjMCAwIDAtLjEuMS0uMUw4OTkgNzMzLjRjMTQuNS0yMS43IDI3LjYtNDQuNCAzOS4zLTY4bC01MzcuNC0yNjVjMCAwIDAtLjEuMC0uMWw1NjcuNCAxOTIuNmM4LjMtMjQuNiAxNS4xLTQ5LjkgMjAuMi03NS44TDQwMSA0MDAuMmMwIDAgMC0uMS4wLS4xTDk5OC43IDQzOS4yeiIvPjwvZz48L3N2Zz4=);background-attachment:fixed;background-size:cover;background-position:center}</style>ZZZZZZZZz
```

base64 encoding increase svg size.

**Comment by tdewolff** [comment] 2018-04-14 06:28
This is related to https://github.com/tdewolff/minify/issues/180, basically the spec doesn't say which characters need percent-encoding, so all are being applied. Some minifiers use only a subset (based on what?), which I need to investigate as it seems against the spec. I will close this as a duplicate of #180

**Closed by tdewolff** 2018-04-14 06:28 UTC
