### ISSUE TITLE
must specify --bundle for multiple input files with stdout destination

### ISSUE THREAD

**Issue by elandorr** [tdewolff/minify#683] opened 2024-03-13 09:07 UTC
```
minify --bundle *.foo
ERROR: must specify --bundle for multiple input files with stdout destination
minify v2.20.19
```

Not an option I ever used. Randomly discovered this bug just now.

**Comment by tdewolff** [comment] 2024-03-13 20:20
It's not a bug, you specify multiple inputs but only one output (stdout), if you don't bundle the input files, how should it output the minified files to one destination? ;-)

**Comment by tdewolff** [comment] 2024-03-14 01:27
Ah very sorry, I didn't read your issue well. Thanks for raising this one! Should be fixed now :-)

**Closed as completed** 2024-03-14 01:26 UTC
