### ISSUE TITLE
Invalid CSS and closing style tag

### ISSUE THREAD

**Issue by pageben** [tdewolff/minify#437] opened 2021-09-14 16:47 UTC
I'm running the following invalid inline style through the html minifier, and am finding it breaks the closing style tag:
`<style>li</style>`

After minification, the bad css seems to be causing the closing tag's slash to instead be a bad character:
`<style type="text/css">li<�style>`

When the browser parses that, the style fails to close, leaving a huge white area on the page since the closing </style> tag isn't used, the rest of the html on the page is assumed to be within the style.

In valid code, that would include curly braces a style like:
`<style>li {foo:bar;}</style>`
But the template language I'm using needs curly braces escaped, so occasionally a dev will fail to escape their curly braces, and some invalid code will get through to the minifer.

I'm trying to write a fallback or find an error rather than render a bad character.  Have you seen this, or are you able to reproduce by trying to minify `<style>li</style>` ?

**Comment by tdewolff** [comment] 2021-09-18 14:17
Thanks for the bug report! I haven't had this problem before, and trying to minify `<style>li</style>` using the HTML minifier (with enabled CSS minifier) does not produce this issue. E.g.:

```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Test</title>
  <style type="text/css">li</style>
</head>
<body>
</body>
</html>
```

is minified to

```html
<!doctype html><html lang=en><meta charset=utf-8><title>Test</title><style>li</style>
```

Do you have an example that reproduces this error? Does it always happen or only sometimes?

**Comment by tdewolff** [comment] 2021-10-04 14:49
Closing due to being unreproducible, please re-open if this problem persists

**Closed by tdewolff** 2021-10-04 14:49 UTC
