### ISSUE TITLE
Got the corrupted FormValidation after updated to v2.9.17

### ISSUE THREAD

**Issue by huijitec** [tdewolff/minify#419] opened 2021-06-09 02:39 UTC
I'm use the formvalidation (https://formvalidation.io) v1.7.0 for form validation. It seems to be corrupting and stop working when i upgrade the minify from v2.9.13 to v2.9.17, but i cannot figure it out how and where exactly.

For example, the formvalidation always  shows `The phone number is required.` message whatever you input. But when i downgrade the minify to v2.9.13, it is runs well. The html and js code like these in below:

```html
<input class="form-control" type="text" name="phone" autocomplete="off" pattern="^1[2-9][0-9]{9}$" required data-fv-regexp___message="The phone number is wrong." data-fv-not-empty___message="The phone number is required." />
```

```js
var validator = FormValidation.formValidation(
            $form[0],
            {
                plugins: {
                    trigger: new FormValidation.plugins.Trigger(),
                    autoFocus: new FormValidation.plugins.AutoFocus(),
                    bootstrap: new FormValidation.plugins.Bootstrap(),
                    declarative: new FormValidation.plugins.Declarative({
                        html5Input: true,
                    }),
                }
            }
        );
```

**Comment by tdewolff** [comment] 2021-06-23 14:35
Sorry for the late response. I assume you're minifying the FormValidation JavaScript files? Or just the piece of JavaScript that you've posted above? Maybe try with v2.9.18 as there has been a fix for a bug with the JS minifier.

Do you get any errors in the browser's console? Is there any way you could make a small bit of code to reproduce the problem, so that I can test it locally?

**Comment by tdewolff** [comment] 2021-09-09 18:22
I'm unable to reproduce and the bug has potentially been fixed in the mean while. Please re-open if this persists!

**Closed by tdewolff** 2021-09-09 18:22 UTC
