### ISSUE TITLE
Recursive option with in-place output causes all files to be blank

### ISSUE THREAD

**Issue by droidmonkey** [tdewolff/minify#306] opened 2020-05-28 18:35 UTC
The following command causes all files to be blank after the operation completes:

`minify -r -o . .`

This occurs in subfolders only. When running the same command in the subfolder all files minify properly in-place.

**Comment by tdewolff** [comment] 2020-05-29 00:02
Thanks for raising the issue. However, I've tried this locally with a root folder and a sub directory, both containing an HTML file. The files are minified correctly and none end up blank.

Could you please confirm that the latest version of minify works well for you, and if not a specific testcase so I can reproduce this? Thanks!

**Comment by droidmonkey** [comment] 2020-05-29 00:31
I was using the latest version under releases

```
$ minify --version
minify 2.7.4
```

Running in a mingw64 terminal.

**Comment by tdewolff** [comment] 2020-06-01 17:22
I'm really unable to reproduce this, can you see if https://github.com/tdewolff/minify/commit/84383ec719eaeee9c3ddca83784f617275a9c420 fixes this? It might be related as `defer` calls weren't properly made, but there is probably something else wrong...

**Comment by droidmonkey** [comment] 2020-06-04 13:23
Your build fails ☹️ 

https://travis-ci.org/github/tdewolff/minify/jobs/694457180

**Comment by tdewolff** [comment] 2020-06-04 15:13
Yes, you need to use `master` from `tdewolff/parse` too.

**Comment by tdewolff** [comment] 2020-06-08 17:57
I've just released a new version of `minify` and `parse`, see if running v2.7.6 fixes this for you.

**Comment by droidmonkey** [comment] 2020-06-09 11:48
Unfortunately 2.7.6 still doesn't fix the problem. At this time we are just minifying per directory and avoiding the recursive option. If you cannot replicate than you can close the issue.

**Comment by tdewolff** [comment] 2020-06-10 02:11
I will give it another try. Can you explain the smallest case that reproduces this for you?

You run `minify -r -o . .` from say directory `site`. This directory for example has subdirectory `styles` and `scripts`, which contain files that need to be minified. How many subdirectories do you have? Does the `site` directory contain files as well? How many files are in the subdirectories? What file extension do they have?

**Comment by GitHubAdi** [comment] 2020-06-10 07:06
Hi tdewolff,
I can also confirm this behavior with the new minify 2.7.6 on my win7 computer. I have an older version of minify on my computer (I dont klnow the version so I just renamed it to "minifyold.exe") which I could use to compare with the latest version ("minify276.exe") and printed those verbose:

Tom@Win7 MSYS /d
$ ./minify276.exe --version
minify 2.7.6

Tom@Win7 MSYS /d
$ ./minifyold.exe --version
unknown flag: --version
Usage: D:\minifyold.exe [options] [input]

Options:
  -a, --all                          Minify all files, including hidden files and files in hidden directories
      --css-decimals int             Number of decimals to preserve in numbers, -1 is all (default -1)
      --html-keep-default-attrvals   Preserve default attribute values
      --html-keep-document-tags      Preserve html, head and body tags
      --html-keep-end-tags           Preserve all end tags
      --html-keep-whitespace         Preserve whitespace characters but still collapse multiple into one
  -l, --list                         List all accepted filetypes
      --match string                 Filename pattern matching using regular expressions, see https://github.com/google/re2/wiki/Syntax
      --mime string                  Mimetype (text/css, application/javascript, ...), optional for input filenames, has precendence over -type
  -o, --output string                Output file or directory (must have trailing slash), leave blank to use stdout
  -r, --recursive                    Recursively minify directories
      --svg-decimals int             Number of decimals to preserve in numbers, -1 is all (default -1)
      --type string                  Filetype (css, html, js, ...), optional for input filenames
  -u, --update                       Update binary
      --url string                   URL of file to enable URL minification
  -v, --verbose                      Verbose
  -w, --watch                        Watch files and minify upon changes
      --xml-keep-whitespace          Preserve whitespace characters but still collapse multiple into one

Input:
  Files or directories, leave blank to use stdin

Tom@Win7 MSYS /d
$ ls -goR html_test
html_test:
total 48
-rw-r--r-- 1 18343 Jun 10 09:43 1.html
-rw-r--r-- 1 21950 Jun 10 09:43 2.html
drwxr-xr-x 1     0 Jun 10 09:34 html

html_test/html:
total 88
-rw-r--r-- 1 18343 Jun 10 09:43 1.html
-rw-r--r-- 1 21950 Jun 10 09:43 2.html
-rw-r--r-- 1 18343 Jun 10 09:43 3.html
-rw-r--r-- 1 21950 Jun 10 09:43 4.html

Tom@Win7 MSYS /d
$ ./minifyold -vr html_test -o html_test
INFO: infer mimetype from file extensions
INFO: expanding directory html_test/ recursively
INFO: minify 6 input files
INFO: minify to output directory html_test/
INFO: (       0s,  18 kB,  95.2%, Inf MB/s) - html_test/1.html
INFO: (     10ms,  21 kB,  93.8%, 2.2 MB/s) - html_test/2.html
INFO: (       0s,  18 kB,  95.2%, Inf MB/s) - html_test/html/1.html
INFO: (       0s,  21 kB,  93.8%, Inf MB/s) - html_test/html/2.html
INFO: (       0s,  18 kB,  95.2%, Inf MB/s) - html_test/html/3.html
INFO: (       0s,  21 kB,  93.8%, Inf MB/s) - html_test/html/4.html
INFO: 10ms total

Tom@Win7 MSYS /d
$ ./minify276 -vr html_test -o html_test
INFO: infer mimetype from file extensions
INFO: minify to output directory html_test/
INFO: (       0s,    0 B,    0 B, 100.0%, Inf MB/s) - html_test\1.html to html_test/1.html
INFO: (       0s,    0 B,    0 B, 100.0%, Inf MB/s) - html_test\2.html to html_test/2.html
INFO: (       0s,    0 B,    0 B, 100.0%, Inf MB/s) - html_test\html\1.html to html_test/html/1.html
INFO: (       0s,    0 B,    0 B, 100.0%, Inf MB/s) - html_test\html\2.html to html_test/html/2.html
INFO: (       0s,    0 B,    0 B, 100.0%, Inf MB/s) - html_test\html\3.html to html_test/html/3.html
INFO: (       0s,    0 B,    0 B, 100.0%, Inf MB/s) - html_test\html\4.html to html_test/html/4.html
INFO: 0s total

Tom@Win7 MSYS /d
$ cp -r html_tmp/* html_test

Tom@Win7 MSYS /d
$ ls -goR html_test
html_test:
total 48
-rw-r--r-- 1 18343 Jun 10 09:44 1.html
-rw-r--r-- 1 21950 Jun 10 09:44 2.html
drwxr-xr-x 1     0 Jun 10 09:44 html

html_test/html:
total 88
-rw-r--r-- 1 18343 Jun 10 09:44 1.html
-rw-r--r-- 1 21950 Jun 10 09:44 2.html
-rw-r--r-- 1 18343 Jun 10 09:44 3.html
-rw-r--r-- 1 21950 Jun 10 09:44 4.html

Tom@Win7 MSYS /d
$ cd html_test

Tom@Win7 MSYS /d/html_test
$ ../minifyold -vr . -o .
INFO: infer mimetype from file extensions
INFO: expanding directory ./ recursively
INFO: minify 6 input files
INFO: minify to current working directory
INFO: (       0s,  18 kB,  95.2%, Inf MB/s) - 1.html
INFO: (     10ms,  21 kB,  93.8%, 2.2 MB/s) - 2.html
INFO: (       0s,  18 kB,  95.2%, Inf MB/s) - html/1.html
INFO: (       0s,  21 kB,  93.8%, Inf MB/s) - html/2.html
INFO: (       0s,  18 kB,  95.2%, Inf MB/s) - html/3.html
INFO: (       0s,  21 kB,  93.8%, Inf MB/s) - html/4.html
INFO: 17.0004ms total

Tom@Win7 MSYS /d/html_test
$ ../minify276 -vr . -o .
INFO: infer mimetype from file extensions
INFO: minify to current working directory
INFO: (       0s,  18 kB,  17 kB,  99.5%, Inf MB/s) - 1.html
INFO: (     10ms,  21 kB,  20 kB,  98.7%, 2.1 MB/s) - 2.html
INFO: (       0s,    0 B,    0 B, 100.0%, Inf MB/s) - html\1.html to html/1.html
INFO: (       0s,    0 B,    0 B, 100.0%, Inf MB/s) - html\2.html to html/2.html
INFO: (       0s,    0 B,    0 B, 100.0%, Inf MB/s) - html\3.html to html/3.html
INFO: (       0s,    0 B,    0 B, 100.0%, Inf MB/s) - html\4.html to html/4.html
INFO: 10ms total

Tom@Win7 MSYS /d/html_test
$ cp -r ../html_tmp/* .

Tom@Win7 MSYS /d/html_test
$ ../minifyold -vr html/1.html -o html/1.html
INFO: infer mimetype from file extensions
INFO: minify input file html/1.html
INFO: minify to output file html/1.html
INFO: (       0s,  18 kB,  95.2%, Inf MB/s) - html/1.html
INFO: 0s total

Tom@Win7 MSYS /d/html_test
$ ../minify276 -vr html/2.html -o html/2.html
INFO: infer mimetype from file extensions
INFO: minify to output file html/2.html
INFO: (       0s,  22 kB,  20 kB,  92.6%, Inf MB/s) - html/2.html
INFO: 0s total

Tom@Win7 MSYS /d/html_test
$ ls -goR
.:
total 48
-rw-r--r-- 1 18343 Jun 10 09:46 1.html
-rw-r--r-- 1 21950 Jun 10 09:46 2.html
drwxr-xr-x 1     0 Jun 10 09:46 html

./html:
total 84
-rw-r--r-- 1 17454 Jun 10 09:46 1.html
-rw-r--r-- 1 20326 Jun 10 09:46 2.html
-rw-r--r-- 1 18343 Jun 10 09:46 3.html
-rw-r--r-- 1 21950 Jun 10 09:46 4.html

Tom@Win7 MSYS /d/html_test
$ cd ..

Tom@Win7 MSYS /d
$ ./minifyold -vrs html_test -o html_sync
unknown shorthand flag: 's' in -s
Usage: D:\minifyold.exe [options] [input]

Options:
  -a, --all                          Minify all files, including hidden files and files in hidden directories
      --css-decimals int             Number of decimals to preserve in numbers, -1 is all (default -1)
      --html-keep-default-attrvals   Preserve default attribute values
      --html-keep-document-tags      Preserve html, head and body tags
      --html-keep-end-tags           Preserve all end tags
      --html-keep-whitespace         Preserve whitespace characters but still collapse multiple into one
  -l, --list                         List all accepted filetypes
      --match string                 Filename pattern matching using regular expressions, see https://github.com/google/re2/wiki/Syntax
      --mime string                  Mimetype (text/css, application/javascript, ...), optional for input filenames, has precendence over -type
  -o, --output string                Output file or directory (must have trailing slash), leave blank to use stdout
  -r, --recursive                    Recursively minify directories
      --svg-decimals int             Number of decimals to preserve in numbers, -1 is all (default -1)
      --type string                  Filetype (css, html, js, ...), optional for input filenames
  -u, --update                       Update binary
      --url string                   URL of file to enable URL minification
  -v, --verbose                      Verbose
  -w, --watch                        Watch files and minify upon changes
      --xml-keep-whitespace          Preserve whitespace characters but still collapse multiple into one

Input:
  Files or directories, leave blank to use stdin

Tom@Win7 MSYS /d
$ ./minify276 -vrs html_test -o html_sync
INFO: infer mimetype from file extensions
ERROR: --sync requires destination to be a directory

Tom@Win7 MSYS /d
$ ./minify276 -vrs html_test -o html_sync/
INFO: infer mimetype from file extensions
INFO: minify to output directory html_sync/
INFO: (       0s,  18 kB,  17 kB,  94.7%, Inf MB/s) - html_test\1.html to html_sync/1.html
INFO: (       0s,  22 kB,  20 kB,  92.6%, Inf MB/s) - html_test\2.html to html_sync/2.html
INFO: (       0s,  18 kB,  17 kB,  99.5%, Inf MB/s) - html_test\html\1.html to html_sync/html/1.html
INFO: (       0s,  20 kB,  20 kB, 100.0%, Inf MB/s) - html_test\html\2.html to html_sync/html/2.html
INFO: (     10ms,  18 kB,  17 kB,  94.7%, 1.8 MB/s) - html_test\html\3.html to html_sync/html/3.html
INFO: ( 1.0001ms,  22 kB,  20 kB,  92.6%,  22 MB/s) - html_test\html\4.html to html_sync/html/4.html
INFO: 12.0001ms total

Tom@Win7 MSYS /d
$ ls -goR html_test
html_test:
total 48
-rw-r--r-- 1 18343 Jun 10 09:46 1.html
-rw-r--r-- 1 21950 Jun 10 09:46 2.html
drwxr-xr-x 1     0 Jun 10 09:46 html

html_test/html:
total 84
-rw-r--r-- 1 17454 Jun 10 09:46 1.html
-rw-r--r-- 1 20326 Jun 10 09:46 2.html
-rw-r--r-- 1 18343 Jun 10 09:46 3.html
-rw-r--r-- 1 21950 Jun 10 09:46 4.html

Tom@Win7 MSYS /d
$ ls -goR html_sync
html_sync:
total 44
-rw-r--r-- 1 17372 Jun 10 09:47 1.html
-rw-r--r-- 1 20326 Jun 10 09:47 2.html
drwxr-xr-x 1     0 Jun 10 09:47 html

html_sync/html:
total 80
-rw-r--r-- 1 17372 Jun 10 09:47 1.html
-rw-r--r-- 1 20326 Jun 10 09:47 2.html
-rw-r--r-- 1 17372 Jun 10 09:47 3.html
-rw-r--r-- 1 20326 Jun 10 09:47 4.html

So -r:
- works fine on a file
- works fine with --sync
- works fine on the files in the current directory
- ! blanks the files on the sub-directories !

I hope this can help you pinpoint what might be the issue. As I dont know the version of my older minify.exe, I just left the --help in this verbose to maybe help you identify it if necessary.

Have a good day and thanks a lot for your hard work,

Tom.

**Comment by GitHubAdi** [comment] 2020-06-10 07:34
As a last test, I used -rs but with the same output directory instead of a different one, and the results are the same as using -r without --sync:

Tom@Win7 MSYS /d
$ ls -goR html_test
html_test:
total 48
-rw-r--r-- 1 18343 Jun 10 10:27 1.html
-rw-r--r-- 1 21950 Jun 10 10:27 2.html
drwxr-xr-x 1     0 Jun 10 09:46 html

html_test/html:
total 88
-rw-r--r-- 1 18343 Jun 10 10:27 1.html
-rw-r--r-- 1 21950 Jun 10 10:27 2.html
-rw-r--r-- 1 18343 Jun 10 10:27 3.html
-rw-r--r-- 1 21950 Jun 10 10:27 4.html

Tom@Win7 MSYS /d
$ ./minify276 -vrs html_test -o html_test/
INFO: infer mimetype from file extensions
INFO: minify to output directory html_test/
INFO: (       0s,    0 B,    0 B, 100.0%, Inf MB/s) - html_test\1.html to html_test/1.html
INFO: (       0s,    0 B,    0 B, 100.0%, Inf MB/s) - html_test\2.html to html_test/2.html
INFO: (       0s,    0 B,    0 B, 100.0%, Inf MB/s) - html_test\html\1.html to html_test/html/1.html
INFO: (       0s,    0 B,    0 B, 100.0%, Inf MB/s) - html_test\html\2.html to html_test/html/2.html
INFO: (       0s,    0 B,    0 B, 100.0%, Inf MB/s) - html_test\html\3.html to html_test/html/3.html
INFO: (       0s,    0 B,    0 B, 100.0%, Inf MB/s) - html_test\html\4.html to html_test/html/4.html
INFO: 0s total

**Comment by GitHubAdi** [comment] 2020-06-10 09:56
I went through your previous releases and realized that this issue started to occur with version 2.7.0 as it still worked as expected with version 2.6.2:

Tom@Win7 MSYS /d
$ ./minify262 --version
minify version 2.6.2

Tom@Win7 MSYS /d
$ ./minify270 --version
minify version 2.7.0

Tom@Win7 MSYS /d
$ cp -r html_tmp/* html_test

Tom@Win7 MSYS /d
$ ls -goR html_test
html_test:
total 48
-rw-r--r-- 1 18343 Jun 10 12:46 1.html
-rw-r--r-- 1 21950 Jun 10 12:46 2.html
drwxr-xr-x 1     0 Jun 10 12:45 html

html_test/html:
total 88
-rw-r--r-- 1 18343 Jun 10 12:46 1.html
-rw-r--r-- 1 21950 Jun 10 12:46 2.html
-rw-r--r-- 1 18343 Jun 10 12:46 3.html
-rw-r--r-- 1 21950 Jun 10 12:46 4.html

Tom@Win7 MSYS /d
$ ./minify262 -vr html_test -o html_test
INFO: infer mimetype from file extensions
INFO: expanding directory html_test/ recursively
INFO: minify 6 input files
INFO: minify to output directory html_test/
INFO: (      1ms,  17 kB,  94.7%,  18 MB/s) - html_test/1.html
INFO: ( 1.0001ms,  20 kB,  92.6%,  22 MB/s) - html_test/2.html
INFO: (       0s,  17 kB,  94.7%, Inf MB/s) - html_test/html/1.html
INFO: ( 1.0001ms,  20 kB,  92.6%,  22 MB/s) - html_test/html/2.html
INFO: (       0s,  17 kB,  94.7%, Inf MB/s) - html_test/html/3.html
INFO: (       0s,  20 kB,  92.6%, Inf MB/s) - html_test/html/4.html
INFO: 8.0004ms total

Tom@Win7 MSYS /d
$ ls -goR html_test
html_test:
total 44
-rw-r--r-- 1 17372 Jun 10 12:46 1.html
-rw-r--r-- 1 20326 Jun 10 12:46 2.html
drwxr-xr-x 1     0 Jun 10 12:46 html

html_test/html:
total 80
-rw-r--r-- 1 17372 Jun 10 12:46 1.html
-rw-r--r-- 1 20326 Jun 10 12:46 2.html
-rw-r--r-- 1 17372 Jun 10 12:46 3.html
-rw-r--r-- 1 20326 Jun 10 12:46 4.html

Tom@Win7 MSYS /d
$ cp -r html_tmp/* html_test

Tom@Win7 MSYS /d
$ ./minify270 -vr html_test -o html_test
INFO: infer mimetype from file extensions
INFO: minify to output directory html_test/
INFO: (       0s,    0 B,    0 B, 100.0%, Inf MB/s) - html_test\1.html to html_test/1.html
INFO: (       0s,    0 B,    0 B, 100.0%, Inf MB/s) - html_test\2.html to html_test/2.html
INFO: (       0s,    0 B,    0 B, 100.0%, Inf MB/s) - html_test\html\1.html to html_test/html/1.html
INFO: (       0s,    0 B,    0 B, 100.0%, Inf MB/s) - html_test\html\2.html to html_test/html/2.html
INFO: (       0s,    0 B,    0 B, 100.0%, Inf MB/s) - html_test\html\3.html to html_test/html/3.html
INFO: (       0s,    0 B,    0 B, 100.0%, Inf MB/s) - html_test\html\4.html to html_test/html/4.html
INFO: 10ms total

Tom@Win7 MSYS /d
$ ls -goR html_test
html_test:
total 4
-rw-r--r-- 1 0 Jun 10 12:47 1.html
-rw-r--r-- 1 0 Jun 10 12:47 2.html
drwxr-xr-x 1 0 Jun 10 12:46 html

html_test/html:
total 0
-rw-r--r-- 1 0 Jun 10 12:47 1.html
-rw-r--r-- 1 0 Jun 10 12:47 2.html
-rw-r--r-- 1 0 Jun 10 12:47 3.html
-rw-r--r-- 1 0 Jun 10 12:47 4.html

If there is anything else I can do to help you better tackle this issue, dont hesitate to let me know.

**Comment by tdewolff** [comment] 2020-06-11 21:13
Thanks for the hard work Tom! I have tried the exact same test case as you described, but neither `master` nor `v2.7.0` gives me empty files. Given that you work on Windows the problem is very likely `\` versus `/`! Good catch, and thanks for finding the release where the error pops up.

The `--sync` command in https://github.com/tdewolff/minify/commit/647760764b6e93402208d6b74b4d3d80237ef5e2 does not get used when we use the same output directory in https://github.com/tdewolff/minify/commit/e398b86bae1634c5e8b812558f3c357d59696a73. The relevant commit is probably https://github.com/tdewolff/minify/commit/2a0c64f045ef7faf6397b30067aed64511292fd3 where at the old line 437 we used to call `filepath.ToSlash` but at the new line 426 we don't.

I'm install Windows10 in a VM and see if I can fix this good. There seems to be some superfluous usage of `ToSlash` etcetera and I want to get it right.

**Comment by droidmonkey** [comment] 2020-06-11 21:20
I will also add you should never be minifying to an empty file, there should be an error catch there to prevent blasting people's data away. Luckily we live in Git, but maybe not so much with others.

**Comment by tdewolff** [comment] 2020-06-11 23:22
Fixed in 2cf57a7 (verified in Windows10), this will also fix overwriting empty files. In short, the input filepath used backslashes while the output filepath used foward slashes, thus `input != output` and a tmp file to write to isn't created (which is necessary when you simultaneously read and overwrite a file). Please let me know if this fixes it and if not please reopen the issue, thanks for the detailed report!

**Closed by tdewolff** 2020-06-11 23:22 UTC

**Comment by GitHubAdi** [comment] 2020-06-12 09:46
Glad I could help and thanks for the fast fix.
I understand the need to get as much information as possible in order to successfully hunt bugs and I am sure that if droidmonkey had given you a bit more details about this issue, it wouldn't have taken you 2 weeks to close it; but less than 2 days as you just did after getting my msgs.
I'll wait for the new release and let you know how it goes :+1:

**Comment by droidmonkey** [comment] 2020-06-12 10:37
Ok @GitHubAdi, thanks for the totally unnecessary insult. I provided sufficient information to reproduce the problem and answered all the questions asked.

**Comment by GitHubAdi** [comment] 2020-06-12 11:33
@droidmonkey, I am sorry that you felt insulted, it was not against you but instead a praise to tdewolf's speedy fix. In any case, I am glad that this issue was successfully closed in such a timely manner and I wish both tdewolf  and you as well as your keepassxc friend @phoerious all the best.
