### ISSUE TITLE
JS minify error: too many nested expressions

### ISSUE THREAD

**Issue by jmooring** [tdewolff/minify#451] opened 2022-01-13 17:17 UTC
Tested with v2.9.27.

```text
too many nested expressions on line 1 and column 137156
    1: ...}(t,e))),Xe()}var o},Js.prototype.invoke_...
                              ^
```

[test.js.txt](https://github.com/tdewolff/minify/files/7864641/test.js.txt)

Reference:
<https://discourse.gohugo.io/t/build-failure-with-0-92/36523>

**Comment by jmooring** [comment] 2022-01-13 17:21
This _appears_ to be a regression introduced in v2.9.17.

**Comment by tdewolff** [comment] 2022-01-13 19:59
Thanks Joe, I'm on it!

**Comment by tdewolff** [comment] 2022-01-13 20:09
Looks like it is not so much a bug, but a hard limit to prevent abuse. The problem is that the file in question has an expression of comma-operators that has more than 1000 elements (ie. `a,b,c,d,...,AA,BB` of length 1000). Since this creates a tree of a 1000 branches and leaves, that is fairly inefficient (which is why the limit is there in the first place, to prevent memory trouble).

The solution is to parse comma-operators as a list and not a tree.

**Comment by tdewolff** [comment] 2022-01-13 20:53
Should be fixed now, please advice if you run into additional problems

**Closed** 2022-01-13 20:52 UTC

**Comment by jmooring** [comment] 2022-01-14 01:16
Thanks!

**Comment by ylazy** [comment] 2024-11-05 09:56
@tdewolff I'm facing this issue in the latest release (2.21.1):
```
minify.exe --css-precision 0 --html-keep-conditional-comments --html-keep-default-attrvals --html-keep-document-tags --html-keep-end-tags --html-keep-quotes --html-keep-special-comments --js-keep-var-names --js-precision 0 --json-keep-numbers --json-precision 0 --svg-precision 0 --output "C:\Users\admin\Downloads\2000x1200\index.min.js" "index.js"
```
```
Error minimizing index.js:
"minify.exe" --css-precision 0 --html-keep-conditional-comments --html-keep-default-attrvals --html-keep-document-tags --html-keep-end-tags --html-keep-quotes --html-keep-special-comments --js-keep-var-names --js-precision 0 --json-keep-numbers --json-precision 0 --svg-precision 0 --output "C:\Users\admin\Downloads\2000x1200\index.js" "C:\Users\admin\Downloads\2000x1200\index.js"
ERROR: cannot minify C:\Users\admin\Downloads\2000x1200\index.js: too many nested expressions on line 678 and column 15528
  678: ...y:162.2156}).wait(1).to({graphics:mask_gr...
```

[index.zip](https://github.com/user-attachments/files/17630415/index.zip)

Please check this!
Thank you!

**Comment by tdewolff** [comment] 2024-11-05 14:14
That is a huge concatenation of member operators (dot operators). I don't think this could be fixed like we did with the comma operator. But perhaps we could make the ExprLimit a variable you can change. Let me see if I can get this in this week.

**Comment by tdewolff** [comment] 2025-01-19 17:20
I've added this in the `parse` package and should soon be used in `minify`.

**Comment by ylazy** [comment] 2025-05-23 03:40
Hi @tdewolff I've tried the latest release and can't find any new command line option to specify the limit. Can you help?
Thank you!
